<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7cd4ae28-224b-4d44-9962-717b9e53273b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
    <ApplicationIcon>Ternary-teal.ico</ApplicationIcon>
    <PackageIcon>Ternary-teal.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Ternary-teal.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\resources\Ternary-teal.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" />
    <PackageReference Include="Duende.AccessTokenManagement" />
    <PackageReference Include="Duende.AccessTokenManagement.OpenIdConnect" />
    <PackageReference Include="HyRest" />
    <PackageReference Include="HyRest.DependencyInjection" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <PackageReference Include="Ternary.Extensions.Logging" />
  </ItemGroup>

</Project>
